version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wowwendor
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - wordpress_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_container
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wowwendor
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: pass
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - wordpress_network

volumes:
  db_data:

networks:
  wordpress_network:
    driver: bridge
